apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-user-api
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-user-api
  template:
    metadata:
      labels:
        app: create-user-api
    spec:
      containers:
        - name: api
          image: ghcr.io/leanjperalta/python-create-user-api:2adb8a7614a6c9f50c4fa91f3376fbc5ea8dcea3
          ports:
            - containerPort: 8000
          env:
            - name: LP_PASS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: lp_pass
