apiVersion: v1
kind: Service
metadata:
  name: create-user-api
  namespace: stage
spec:
  selector:
    app: create-user-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP  # Change to LoadBalancer if needed
